spring.application.name=product-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=${SERVER_PORT:8081}

# url location of the eureka server registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# properties for registering with eureka server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#inorder to log the tracing the orderclient request
logging.level.com.training.productservice.client=DEBUG

order-service.base-url=${ORDER_SERVICE_URL:http://localhost:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/productdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.url=/openapi.yaml
springdoc.packages-to-scan=com.training.productservice.none
